accelerator: ddp
accumulate_grad_batches: 64
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 8
benchmark: true
check_val_every_n_epoch: 1
checkpoint_callback: true
data_dir: data
default_root_dir: null
deterministic: false
distributed_backend: null
enable_pl_optimizer: true
fast_dev_run: false
flush_logs_every_n_steps: 100
gpt2_model_type: gpt2
gpus: 8
gradient_checkpointing: false
gradient_clip_val: 0
infile: meme_data.tsv
learning_rate: 5.0e-05
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
max_epochs: 1
max_steps: null
min_epochs: 1
min_steps: null
move_metrics_to_cpu: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
outfile: data.pickle
overfit_batches: 0.0
plugins: ddp_sharded
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
seed_everything: true
split_ratios:
- 0.8
- 0.1
- 0.1
sync_batchnorm: false
terminate_on_nan: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weights_save_path: null
weights_summary: top
